name: Release
on:
  workflow_dispatch:
      inputs:
        version:
          description: "<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease"
          required: true
jobs:
  Release-To-NPM:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.22.1'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          echo "Running NPM Install"
          npm install
          echo "Running Tests"
          npm test
          echo "Building Library"
          npm run build
          git config --global user.name 'Release Workflow'
          git config --global user.email 'release-workflow@users.noreply.github.com'
          echo "Incrementing version"
          npm version ${{ github.event.inputs.version }}
          echo "Pushing Version Change"
          git push --follow-tags
          echo "Publishing to NPM"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}